apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-task
spec:
  steps:
    - name: echo-first
      image: ubuntu
      command:
        - echo
      args:
        - "Executing first"
    - name: echo-second
      image: ubuntu
      command:
        - echo
      args:
        - "Executing second"